// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMz2egL99El9Xh-udDa_2V6z9LAD-C6VA',
    appId: '1:890575293192:web:afe63955224f3ff8a83abd',
    messagingSenderId: '890575293192',
    projectId: 'reblend-4d60b',
    authDomain: 'reblend-4d60b.firebaseapp.com',
    storageBucket: 'reblend-4d60b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkv43SmJAH3naxk_B6_GvktKRtjn261P4',
    appId: '1:890575293192:android:6dd513fa9f271874a83abd',
    messagingSenderId: '890575293192',
    projectId: 'reblend-4d60b',
    storageBucket: 'reblend-4d60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRd_HohhAgoILuXPe9oi2O4mH_35JEOjQ',
    appId: '1:890575293192:ios:ee66ad3e1c23e6c3a83abd',
    messagingSenderId: '890575293192',
    projectId: 'reblend-4d60b',
    storageBucket: 'reblend-4d60b.firebasestorage.app',
    iosClientId: '890575293192-j5k5sp72qs4ps9eqrvpnrg7de1ovkii8.apps.googleusercontent.com',
    iosBundleId: 'com.example.reblend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRd_HohhAgoILuXPe9oi2O4mH_35JEOjQ',
    appId: '1:890575293192:ios:ee66ad3e1c23e6c3a83abd',
    messagingSenderId: '890575293192',
    projectId: 'reblend-4d60b',
    storageBucket: 'reblend-4d60b.firebasestorage.app',
    iosClientId: '890575293192-j5k5sp72qs4ps9eqrvpnrg7de1ovkii8.apps.googleusercontent.com',
    iosBundleId: 'com.example.reblend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMz2egL99El9Xh-udDa_2V6z9LAD-C6VA',
    appId: '1:890575293192:web:cf6cb25be0e0cf05a83abd',
    messagingSenderId: '890575293192',
    projectId: 'reblend-4d60b',
    authDomain: 'reblend-4d60b.firebaseapp.com',
    storageBucket: 'reblend-4d60b.firebasestorage.app',
  );

}